name: CI for Go code  #Naming the workflow
on: #for event triggering
  push:
    branches: [main] #add with comma for more branches to monitor
  pull_request:
    branches: [main]
    
jobs: #job to execute?
  build: #name of the job
    name: Load OS #name for printing
    runs-on: ubuntu-latest #specify os in the virtual machine
    steps: 
    - name: Print hello
      run: | #run terminal command
        ls
        echo Hello!!
  
